apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-odm-argocd
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/zdmooc/odm_demo.git
    targetRevision: main
    path: manifests/odm
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-odm-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
